### ISSUE TITLE
--flac Broken Length/Bitrate

### ISSUE THREAD

**Issue by HeartbeatingForCenturies** [scdl-org/scdl#503]
> scdl --flac -l https://soundcloud.com/57v/original
> Soundcloud Downloader
> Found a track
> Downloading copy
> Downloading the original file.
> Creating the ffmpeg pipe...
> Encoding..
> Receiving the streaming response
>  93%|███████████████████████████████████████████████████████████████████████████████████████████████       | 88.0/94.453125 [00:00<00:00, 221.52Kb/s]
>  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎    | 1.0/1.045 [00:00<00:00,  2.45s/s]
> Applying metadata...
> [1856917890] saves - copy.flac Downloaded.

Showing for both MusicBee and TagScanner
[Unknown Bitrate] 0kbs 
[Unknown Length] 00:00 Length
Artwork not showing on both applications.

`scdl --version
v2.11.0`

`ffmpeg version N-113193-g59686eaf33-20240103 Copyright (c) 2000-2024 the FFmpeg developers`

**Comment by 7x11x13** [comment]
Thanks for the report, should be fixed in v2.11.1
