### ISSUE TITLE
--flac CLI option results in lossy audio file

### ISSUE THREAD

**Issue by mechabubba** [scdl-org/scdl#508]
Using the `--flac` command line option results in the returned file to be encoded with the lossy AAC codec in an M4A container instead of FLAC. This is a little misleading. 

```
$ scdl --flac --auth-token <AUTH TOKEN> -l https://soundcloud.com/ctoonlink/word-shop
Soundcloud Downloader
Found a track
Downloading Word Shop
Creating the ffmpeg pipe...
Encoding..
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 178.005/178.005 [00:01<00:00, 98.31s/s]
Applying metadata...
Word Shop.m4a Downloaded.
```

File info taken from foobar2000;
```
Items Selected: 1
Duration: 2:58.005 (8 544 256 samples)
Sample rate: 48000 Hz
Channels: 2
Bitrate: 255 kbps
Codec: AAC
Codec profile: AAC LC
Encoding: lossy
```
This was done with a SoundCloud Go+ subscription. I've additionally set my SoundCloud account to prefer high-quality audio, but to no avail.

**Comment by 7x11x13** [comment]
See https://github.com/scdl-org/scdl/issues/461#issuecomment-2211324371
