### ISSUE TITLE
soundcloud adds 160k aac for free tier, SCDL can't differentiate between the GO+ hls or the free one

### ISSUE THREAD

**Issue by HeartbeatingForCenturies** [scdl-org/scdl#524]
scdl isn't preferring the go+ version its just grabbing the 160k aac when there is a 256 transcode avail

only noticed this as of today so must be a new change

https://soundcloud.com/splitxx/good-fellas-rmx

**Comment by HeartbeatingForCenturies** [comment]
this change seems to be reverted now

**Comment by HeartbeatingForCenturies** [comment]
and its back, @7x11x13

**Comment by 7x11x13** [comment]
Seems to be DRM protected, probably won't be implemented

**Comment by 7x11x13** [comment]
So what's happening is it grabs the format "aac_1_0" which is not DRM protected, it seems to be 160kbps AAC. The new "aac_256k" format they added is DRM protected, and we can't decrypt it (legally).

**Comment by jz1** [comment]
some aac_256k and 160kbps is not DRM protected, i think they are still A-B testing what they gonna do.

i'm running my own custom fork of a old version, how i handle it there is i made a priority array with the different formats i prefer first to last, and as last im checking if the stream is encrypted by ['media']['transcodings']["format"]['protocol'] otherways it will skip to the next transcoding in priority, so that incase aac_256k is unencrypted it can still grab it, but if its encrypted it will not grab it. The aac_256k seems also to got more track information data

example link where the aac_160k and aac_256k are unencrypted: https://soundcloud.com/inspiredbytrees/donny-carr-terra-paul-hazendonk-riigs-remix

**Comment by HeartbeatingForCenturies** [comment]
So from what I've gathered is on December 2nd Soundcloud decided to add two new transcodes, "aac_160" & "aac_256k" (which replaced the Go+ "aac_hq" / "aac_1_0" for anything after December 2nd)

the script currently is finding anything under "aac" and downloading the first one it can find

**Comment by HeartbeatingForCenturies** [comment]
`
# Filter HLS transcodings
transcodings = [t for t in track.media.transcodings if t.format.protocol == "hls"]
if not transcodings:
    raise SoundCloudException(f"No HLS transcodings available for {track.permalink_url}")

# Define prioritized presets
prioritized_presets = [
    ("aac_256k", "m4a"),
    ("aac_1_0", "m4a"),
    ("aac_hq", "m4a"),
    ("aac_160k", "m4a"),
    ("mp3_1_0", "mp3"),
    ("mp3_0_1", "mp3"),
    ("mp3_0_0", "mp3"),
    ("mp3_standard", "mp3"),
]

# Restrict to MP3 presets if "onlymp3" is kwargs are set
if kwargs.get("onlymp3"):
    prioritized_presets = [
        ("mp3_1_0", "mp3"),
        ("mp3_0_1", "mp3"),
        ("mp3_0_0", "mp3"),
        ("mp3_standard", "mp3"),
    ]

# Find the best matching transcode
transcoding, ext = next(
    (
        (t, f".{preset_ext}")
        for preset_name, preset_ext in prioritized_presets
        for t in transcodings
        if t.preset == preset_name
    ),
    (None, None),
)

if not transcoding:
    available_presets = [t.preset for t in transcodings]
    raise SoundCloudException(
        f"Could not find valid transcoding. Available presets: {available_presets}"
    )
  `

**Comment by HeartbeatingForCenturies** [comment]
I haven't had any DRM issues with the new transcodes aac_256k & aac_160k as of yet

**Comment by jz1** [comment]
> I haven't had any DRM issues with the new transcodes aac_256k & aac_160k as of yet

random soundcloud track that got a encrypted stream "ctr-encrypted-hls": https://soundcloud.com/billieeilish/the-greatest , but also had some with different mode then ctr (but can't remember which or which links anymore).

**Comment by 7x11x13** [comment]
Pushed a fix to prioritize 256 kbps aac if its not drm protected
